FROM python:3.9

WORKDIR /app

COPY . . 

RUN pip install flask

EXPOSE 5000

CMD ["python", "app.py"]


#############################
# What I fixed in this file #
#############################
# 1. Copy was not on its own line
# 2. Added some whitespaces for readability
#